# Generated by Django 4.2.10 on 2024-03-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_current',
            field=models.BooleanField(default=False, verbose_name='Признак текущей версии'),
        ),
    ]
